version: 3
workdir: internal

allow:
  depOnAnyVendor: true
  deepScan: false

excludeFiles:
  - "^.*_test\\.go$"
  - "^.*mock\\.go$"

components:
  models:
    in: models/**
  services:
    in: services/**
  container:
    in: container
  controllers:
    in: controllers/**
  infrastructure:
    in: infrastructure/**
  clients:
    in:
      - infrastructure/clients/**
  utils:
    in:
      - utils/**

commonComponents:
  - models
  - utils

deps:
  container:
    anyProjectDeps: true

  controllers:
    mayDependOn:
      - services

  services:
    mayDependOn:
      - services

  infrastructure:
    mayDependOn:
      - services

  clients:
    mayDependOn:
      - services
