version: 3
workdir: internal

allow:
  depOnAnyVendor: true
  deepScan: false

excludeFiles:
  - "^.*_test\\.go$"
  - "^.*mock\\.go$"

components:
  models:
    in: models/**

  worker_services:
    in: worker/services/**
  worker_container:
    in: worker/container
  worker_controllers:
    in: worker/controllers/**
  worker_infrastructure:
    in: worker/infrastructure/**
  worker_clients:
    in: worker/infrastructure/clients/**

  scheduler_services:
    in: scheduler/services/**
  scheduler_container:
    in: scheduler/container
  scheduler_controllers:
    in: scheduler/controllers/**
  scheduler_infrastructure:
    in: scheduler/infrastructure/**
  scheduler_clients:
    in: scheduler/infrastructure/clients/**

  utils:
    in:
      - utils/**

commonComponents:
  - models
  - utils

deps:
  container:
    anyProjectDeps: true

  worker_controllers:
    mayDependOn:
      - worker_services

  worker_services:
    mayDependOn:
      - worker_services

  worker_infrastructure:
    mayDependOn:
      - worker_services

  worker_clients:
    mayDependOn:
      - worker_services

  scheduler_controllers:
    mayDependOn:
      - scheduler_services

  scheduler_services:
    mayDependOn:
      - scheduler_services

  scheduler_infrastructure:
    mayDependOn:
      - scheduler_services

  scheduler_clients:
    mayDependOn:
      - scheduler_services
